# Generated by Django 3.2.9 on 2021-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('NATURE', 'nature'), ('CULTURE', 'culture'), ('SCIENCE', 'science')], max_length=50),
        ),
    ]
